/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Scaling.Data
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class InstanceState : TBase
  {
    private string _Id;
    private long _Revision;
    private double _LastResult;

    public string Id
    {
      get
      {
        return _Id;
      }
      set
      {
        __isset.Id = true;
        this._Id = value;
      }
    }

    public long Revision
    {
      get
      {
        return _Revision;
      }
      set
      {
        __isset.Revision = true;
        this._Revision = value;
      }
    }

    public double LastResult
    {
      get
      {
        return _LastResult;
      }
      set
      {
        __isset.LastResult = true;
        this._LastResult = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Id;
      public bool Revision;
      public bool LastResult;
    }

    public InstanceState() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Id = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I64) {
                Revision = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Double) {
                LastResult = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("InstanceState");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Id != null && __isset.Id) {
          field.Name = "Id";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Id);
          oprot.WriteFieldEnd();
        }
        if (__isset.Revision) {
          field.Name = "Revision";
          field.Type = TType.I64;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Revision);
          oprot.WriteFieldEnd();
        }
        if (__isset.LastResult) {
          field.Name = "LastResult";
          field.Type = TType.Double;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(LastResult);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("InstanceState(");
      bool __first = true;
      if (Id != null && __isset.Id) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Id: ");
        __sb.Append(Id);
      }
      if (__isset.Revision) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Revision: ");
        __sb.Append(Revision);
      }
      if (__isset.LastResult) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LastResult: ");
        __sb.Append(LastResult);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
