/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Scaling.Data
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Workpack : TBase
  {
    private InstanceDescriptor _Instance;
    private Operation _OpCode;
    private InputData _Input;

    public InstanceDescriptor Instance
    {
      get
      {
        return _Instance;
      }
      set
      {
        __isset.Instance = true;
        this._Instance = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="Operation"/>
    /// </summary>
    public Operation OpCode
    {
      get
      {
        return _OpCode;
      }
      set
      {
        __isset.OpCode = true;
        this._OpCode = value;
      }
    }

    public InputData Input
    {
      get
      {
        return _Input;
      }
      set
      {
        __isset.Input = true;
        this._Input = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Instance;
      public bool OpCode;
      public bool Input;
    }

    public Workpack() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Instance = new InstanceDescriptor();
                Instance.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                OpCode = (Operation)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Struct) {
                Input = new InputData();
                Input.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Workpack");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Instance != null && __isset.Instance) {
          field.Name = "Instance";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Instance.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.OpCode) {
          field.Name = "OpCode";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)OpCode);
          oprot.WriteFieldEnd();
        }
        if (Input != null && __isset.Input) {
          field.Name = "Input";
          field.Type = TType.Struct;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          Input.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Workpack(");
      bool __first = true;
      if (Instance != null && __isset.Instance) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Instance: ");
        __sb.Append(Instance== null ? "<null>" : Instance.ToString());
      }
      if (__isset.OpCode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OpCode: ");
        __sb.Append(OpCode);
      }
      if (Input != null && __isset.Input) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Input: ");
        __sb.Append(Input== null ? "<null>" : Input.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
